#[derive(Debug, Clone, Copy)]
pub enum Action {
    Insert(char),
    DeletePrev,
    DeleteNext,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    MoveWordLeft,
    MoveWordRight,
    MoveHome,
    MoveEnd,
    PageUp,
    PageDown,
    Save,
    Quit,
    GoToDefinition,
    GoToLine,
    GoBack,
    /// Ctrl-G — enter the "go" chord prefix. The next keystroke
    /// resolves to a destination (see `App::resolve_chord`).
    CtrlGPrefix,
    ShowType,
    Rename,
    ToggleTree,
    ToggleGitDiff,
    ToggleHistory,
    ToggleKeysHelp,
    OpenFile,
    OpenTypeSearch,
    NewFile,
    ToggleAutosave,
    Escape,
}
