#[derive(Debug, Clone, Copy)]
pub enum Action {
    Insert(char),
    DeletePrev,
    DeleteNext,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    MoveWordLeft,
    MoveWordRight,
    MoveHome,
    MoveEnd,
    PageUp,
    PageDown,
    Save,
    Quit,
    GoToDefinition,
    GoBack,
    ToggleTree,
    Escape,
}
